### ISSUE TITLE
🔴 BROKEN: Customers Cannot Use WordPress Plugin & Images Not Displaying

### ISSUE THREAD

**Issue by derrickhorton** [anypay/anypayx.com#24] opened 2022-08-21 15:23 UTC
The graphic for Anypay does not load anymore on WordPress

And "Pay with Anypay" no longer works.

It produces an error that says "Error processing checkout. Please try again."

I learned this from a customer today, and I confirmed it myself at https://derrickhorton.com/shop

<img width="237" alt="Screen Shot 2022-08-21 at 17 10 43" src="https://user-images.githubusercontent.com/4019818/185798355-8c0a5235-5266-48b3-bc18-10abbd6a6e4d.png">

<img width="400" alt="Screen Shot 2022-08-21 at 17 11 31" src="https://user-images.githubusercontent.com/4019818/185798353-6ec9cdf1-50a6-448e-9943-ba7a02f85a87.png">

**Comment by eddiewillers** [comment] 2023-04-19 16:18
Closing as this is a duplicate of issue broken down in https://github.com/anypay/anypay-woocommerce/issues

**Closed as completed by eddiewillers** 2023-04-19 16:18 UTC
Labels: bug, duplicate
